social_media_config.settings:
  path: '/admin/config/system/social-media'
  defaults:
    _form: 'C:\xampp\htdocs\webo\modules\Custom\social_media_config\src\Form\SocialMediaConfigForm.php'
    _title: 'Social Media Configuration'
  requirements:
    _permission: 'administer site configuration'