<?php

use Drupal\Core\Render\Markup;
use Drupal\pcr\PrettyElement;

/**
 * @file
 * This module allows convert default checkbox and radiobutton.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pcr_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.pcr') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t(
        'The Pretty Checkbox Radio module allows the default
        checkbox and radiobutton to be converted to buttons-friendly
        elements.'
      ) . '</p>';
    $output .= '<h3>' . t('Uses') . '</h3>';
    $output .= '<p>' . t(
        'Go to manage form display tab and under widget
        column select "Pretty Check boxes/radio buttons" for Boolean or
        List(text) fields'
      ) . '</p>';
    return $output;
  }
}

/**
 * Implements hook_theme().
 */
function pcr_theme($existing, $type, $theme, $path): array {
  return [
    'elements__pretty_options' => [
      'render element' => 'element',
    ],
    'form_element__pretty_element' => [
      'render element' => 'element',
    ]
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for menu.
 */
function pcr_theme_suggestions_form_element_alter(array &$suggestions, array $variables): void {
  $children = $variables['element']['#children'] instanceof Markup ? $variables['element']['#children']->__toString() : $variables['element']['#children'];
  if (is_string($children) && strpos($children, 'pretty-element')) {
    $suggestions[] = 'form_element__pretty_element';
  }
}

/**
 * Implements hook_element_info_alter().
 */
function pcr_element_info_alter(array &$types): void {
  // The elements to be processed to turn them into a pretty element.
  $candidate_elements = ['checkboxes', 'radios', 'checkbox', 'radio'];

  // Add a process function to each candidate element to modify it.
  foreach ($candidate_elements as $element) {
    if (isset($types[$element])) {
      $types[$element]['#process'][] = [PrettyElement::class, 'process'];
    }
  }
}
