<?php

/**
 * @file
 * Allows to add a block with the links to various social media platforms.
 */

/**
 * Implements hook_theme().
 */
function social_media_platforms_theme($existing, $type, $theme, $path) {
  return [
    'social_media_platforms_links' => [
      'variables' => [
        'display_options' => [],
        'platforms' => [],
        'attributes' => new Attribute(),
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_media_platforms_preprocess_social_media_platforms_links(&$variables) {
  $variables['#attached']['library'][] = 'social_media_platforms/social_media_platforms.theme';
}

/**
 * Implements hook_help().
 */
function social_media_platforms_help($path, $arg) {
  switch ($path) {
    case 'help.page.social_media_platforms':
      return '<p>' . t('This module allows to configure social media platform urls and display them in a block.') . '</p>';
  }
}
